config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'parts/search'
  root 'parts#index'
  resources :car_models, only: [:index, :new, :create] do
    resources :parts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :user
  has_many :parts

  validates :car_model_code, presence: true, format: { with: /\A[0-9]{3}[A-Z]{1}\z/, message: "is 3 half-width numbers + 1 half-width alphabet (uppercase)" }, uniqueness: { case_sensitive: true }
end

app/models/material.rb
class Material < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '材質A' },
    { id: 3, name: '材質B' },
    { id: 4, name: '材質C' },
    { id: 5, name: '材質D' },
    { id: 6, name: '材質E' },
    { id: 7, name: '材質F' },
    { id: 8, name: '材質G' }
  ]

  include ActiveHash::Associations
  has_many :parts
end

app/models/part.rb
class Part < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :car_model
  belongs_to :part_name
  belongs_to :material
  belongs_to :supplier
  has_many_attached :images

  with_options presence: true do
    validates :images, :product_number, :thickness, :weight, :approval_date
  end

  with_options presence: true, numericality: { other_than: 1 } do
    validates  :part_name_id, :material_id, :supplier_id
  end

  validates :product_number, format: { with: /\A[0-9]{5}-[0-9]{5}\z/, message: 'is 5 digits-5 digits (half-width number)' }, uniqueness: { case_sensitive: true }
  validates :thickness, numericality: true, format: { with: /\A[0-9]{0,2}\.[0-9]{2}\z/, message: 'is 2 digits for the decimal part and 2 digits or less for the natural number part' }
  validates :weight, numericality: true, format: { with: /\A[0-9]{0,5}\.[0-9]{2}\z/, message: 'is 2 digits for the decimal part and 5 digits or less for the natural number part' }
  validates :images, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..2.megabytes }

  validate :approval_date_cannot_be_in_the_future
  validate :reference_parts_and_product_number_must_not_be_the_same

  def approval_date_cannot_be_in_the_future
    if approval_date > Date.today
      errors.add(:approval_date, 'is cannot be in the future')
    end
  end
  def reference_parts_and_product_number_must_not_be_the_same
    if reference_parts == product_number
      errors.add(:reference_parts, 'and product number must not be the same')
    end
  end
end

app/models/part_name.rb
class PartName < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'SM_OUTER' },
    { id: 3, name: 'SM_INNER' },
    { id: 4, name: 'ROOF' },
    { id: 5, name: 'RI' },
    { id: 6, name: 'WH' },
    { id: 7, name: 'LWRBACK' },
    { id: 8, name: 'APRON' }
  ]

  include ActiveHash::Associations
  has_many :parts
end

app/models/supplier.rb
class Supplier < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'A社' },
    { id: 3, name: 'B社' },
    { id: 4, name: 'C社' },
    { id: 5, name: 'D社' },
    { id: 6, name: 'E社' },
    { id: 7, name: 'F社' },
    { id: 8, name: 'G社' }
  ]

  include ActiveHash::Associations
  has_many :parts
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :car_models
  has_many :parts

  validates :name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ーa-zA-Z +]+\z/, message: 'is other than numbers, double-byte alphabets, and double-byte spaces' }, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def set_search
    @q = Part.ransack(params[:q])
    @result = @q.result
    @results = @q.result.includes(:car_model)
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/car_models_controller.rb
class CarModelsController < ApplicationController
  def index
    @car_models = CarModel.order(:car_model_code)
  end

  def new
    @car_model = CarModel.new
  end

  def create
    @car_model = CarModel.new(car_model_params)
    @car_model.save
    redirect_to root_path
  end

  private

  def car_model_params
    params.require(:car_model).permit(:car_model_code).merge(user_id: current_user.id)
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :new_part, only: [:new, :create]
  before_action :edit_part, only: [:edit, :update, :destroy]
  before_action :search_part, only: [:index, :search]

  def index
    @car_models = CarModel.order(:car_model_code)
    @parts = Part.all
    set_part_column
    @car_model = CarModel.new
  end

  def new
    @part = Part.new
  end

  def create
    @part = Part.new(part_params)
    if @part.save
      redirect_to car_model_part_path(id: @part)
    else
      render :new
    end
  end

  def show
    @part = Part.find(params[:id])
  end

  def edit
  end

  def update
    if @part.update(part_update_params)
      redirect_to car_model_part_path(id: @part)
    else
      render :edit
    end
  end

  def destroy
    part = Part.find(params[:id])
    part.destroy
    redirect_to root_path
  end

  def search
    @result = @q.result
    @results = @q.result.includes(:car_model)
    if @results.length == 1
      @results.each do |result|
        redirect_to car_model_part_path(result.car_model.id, result.id)
      end
    end
  end

  private

  def part_params
    params.require(:part).permit(:product_number, :part_name_id, :material_id, :thickness, :weight, :supplier_id, :approval_date, :reference_parts, images: []).merge(user_id: current_user.id, car_model_id: params[:car_model_id])
  end

  def part_update_params
    params.require(:part).permit(:car_model_id, :product_number, :part_name_id, :material_id, :thickness, :weight, :supplier_id, :approval_date, :reference_parts, images: [])
  end

  def new_part
    @car_model = CarModel.find(params[:car_model_id])
  end

  def edit_part
    @part = Part.find(params[:id])
    if @part.user_id != current_user.id
      redirect_to car_model_part_path(id: @part)
    end
  end

  def search_part
    @q = Part.ransack(params[:q])
  end

  def set_part_column
    @part_part_name = Part.select('part_name_id').distinct
    @part_product_number = Part.select('product_number').distinct
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompareParts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8475e5d79a.js" crossorigin="anonymous"></script>
    <%# スライダー用 %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/parts/edit.html.erb
<div class="part py-8 px-24 text-2xl">
  <div class="mb-4 text-3xl font-bold">
    <i class="fas fa-cogs"></i> <%= @part.car_model.car_model_code %>の部品を編集する
  </div>
  <%= form_with(model: @part, url: car_model_part_path, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <% @part.images.each do |image| %>
      <%= image_tag image, class: 'delete_image' %>
    <% end %>
    <div class="mt-2 mb-2 text-lg font-bold text-blue-600">
      ※図面を選択すると、登録済みの図面が削除されます
    </div>
    <div class="mb-2">
      <%= f.label :"図面：" %>
      <%= f.file_field :images, name: 'part[images][]', id: 'part_image', style: 'border: none' %>
    </div>
    <div id="image_list"></div>
    <div class="mb-2">
      <%= f.label :"車種：" %>
      <%= f.collection_select(:car_model_id, CarModel.order(:car_model_code), :id, :car_model_code, {}) %>
    </div>
    <div class="mb-2">
      <%= f.label :"部品名：" %>
      <%= f.collection_select(:part_name_id, PartName.all, :id, :name, {}) %>
    </div>
    <div class="mb-2">
      <%= f.label :"品番：" %>
      <%= f.text_field :product_number %>
    </div>
    <div class="mb-2">
      <%= f.label :"材質：" %>
      <%= f.collection_select(:material_id, Material.all, :id, :name, {}) %>
    </div>
    <div class="mb-2">
      <%= f.label :"板厚：" %>
      <%= f.text_field :thickness %>mm
    </div>
    <div class="mb-2">
      <%= f.label :"質量：" %>
      <%= f.text_field :weight %>g
    </div>
    <div class="mb-2">
      <%= f.label :"仕入先：" %>
      <%= f.collection_select(:supplier_id, Supplier.all, :id, :name, {}) %>
    </div>
    <div class="mb-2">
      <%= f.label :"承認日：" %>
      <%= f.date_select :approval_date, start_year: 2000, end_year:(Time.now.year) %>
    </div>
    <div class="mb-4">
      <%= f.label :"参考部品：" %>
      <%= f.collection_select(:reference_parts, Part.order(:product_number), :product_number, :product_number, include_blank: true) %>
    </div>
    <%= f.submit '登録する', class: 'form-submit p-2' %>
  <% end %>
</div>

<div id="page_top">
  <a href="#"><i class="arrow fas fa-arrow-up text-3xl"></i></a>
</div>

app/views/parts/index.html.erb
<div class="wrapper h-screen bg-gray-600">
  <div class="flex">
    <div class="bg-cover mt-4 mb-4 ml-4">
      <%= image_tag 'tacoma.jpg', size: "1000x600" %>
    </div>

    <div class="m-4 w-1/3">
      <dl class="bg-gray-50 rounded-md">
        <div>
          <dt class="text-2xl font-bold"><i class="fas fa-search"></i> 部品を検索・比較する</dt>
          <dd>
            <%= search_form_for @q, url: parts_search_path do |f| %>
            <div class="mb-2">
              <%= f.label :car_model_id_eq, "車種：" %>
              <%= f.collection_select :car_model_id_eq, CarModel.order(:car_model_code), :id, :car_model_code, include_blank: '指定なし' %>
            </div>
            <div class="mb-2">
              <%= f.label :part_name_id_eq, "部品名：" %>
              <%= f.collection_select :part_name_id_eq, PartName.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
            </div>
            <div class="mb-2">
              <%= f.label :product_number_eq, "品番：" %>
              <%= f.search_field :product_number_cont %>
            </div>
            <div class="mb-2">
              <%= f.label :material_id_eq, "材質：" %>
              <%= f.collection_select :material_id_eq, Material.where.not(id: 1), :id, :name, include_blank: '指定なし' %>
            </div>
            <div class="mb-2">
              <%= f.label :thickness, "板厚：" %>
              <label><%= f.radio_button :thickness_lteq, '' %> 指定なし</label>
              <br>
              <label><%= f.radio_button :thickness_lteq, '25.00' %> 25.00mm以下</label>
              <br>
              <label><%= f.radio_button :thickness_lteq, '50.00' %> 50.00mm以下</label>
              <br>
              <label><%= f.radio_button :thickness_lteq, '75.00' %> 75.00mm以下</label>
              <br>
              <label><%= f.radio_button :thickness_lteq, '99.99' %> 99.99mm以下</label>
            </div>
            <div class="mb-2">
              <%= f.label :weight, "質量：" %>
              <label><%= f.radio_button :weight_lteq, '' %> 指定なし</label>
              <br>
              <label><%= f.radio_button :weight_lteq, '25000.00' %> 25,000.00g以下</label>
              <br>
              <label><%= f.radio_button :weight_lteq, '50000.00' %> 50,000.00g以下</label>
              <br>
              <label><%= f.radio_button :weight_lteq, '75000.00' %> 75,000.00g以下</label>
              <br>
              <label><%= f.radio_button :weight_lteq, '99999.99' %> 99,999.99g以下</label>
            </div>
            <div>
              <%= f.label :"仕入先" %>
              <%= f.collection_select :supplier_id_eq, Supplier.where.not(id: 1), :id, :name, include_blank: '指定なし' %>
            </div>
            <div>
            <div class="mb-2">
              <%= f.label :reference_parts_eq, "参考部品：" %>
              <%= f.search_field :reference_parts_cont %>
            </div>
              <button f.submit class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 m-2 px-1 rounded">
                検索・比較する
              </button>
              <button name="button" type="reset" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 m-2 px-1 rounded">
                リセットする
              </button>
            <% end %>
          </dd>
        </div>
        
        <div>
          <dt class="text-2xl font-bold"><i class="fas fa-cogs"></i> 部品を登録する</dt>
          <dd>
            <% if @car_models.length != 0 %>
              <% @car_models.each do |car_model| %>
              <div class="btn m-2 ring ring-gray-300 rounded">
                <%= link_to car_model.car_model_code, new_car_model_part_path(car_model) %>
              </div>
              <% end %>
            <% else %>
              車種を登録してください
            <% end %>
          </dd>
        </div>

        <div>
          <dt class="text-2xl font-bold"><i class="fas fa-car"></i> 車種を登録する</dt>
          <dd>
            <%= form_with model: @car_model, local: true do |f| %>
            <%= render 'shared/error_messages', model: f.object %>
              <%= f.label :"車種：" %>
              <%= f.text_field :car_model_code, placeholder: "300C" %>
              <button f.submit class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 m-2 px-1 rounded">
                登録する
              </button>
            <% end %>
          </dd>
        </div>
      </dl>
    </div>
  </div>
</div>

app/views/parts/new.html.erb
<div class="part py-8 px-24 text-2xl">
  <div class="mb-4 text-3xl font-bold">
    <i class="fas fa-cogs"></i> <%= @car_model.car_model_code %>の部品を登録する
  </div>
  <%= form_with(model: [@car_model, @part], local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="mb-2">
      <%= f.label :"図面：" %>
      <%= f.file_field :images, name: 'part[images][]', id: 'part_image', style: 'border: none' %>
    </div>
    <div id="image_list"></div>
    <div class="mb-2">
      <%= f.label :"部品名：" %>
      <%= f.collection_select(:part_name_id, PartName.all, :id, :name, {}) %>
    </div>
    <div class="mb-2">
      <%= f.label :"品番：" %>
      <%= f.text_field :product_number %>
    </div>
    <div class="mb-2">
      <%= f.label :"材質：" %>
      <%= f.collection_select(:material_id, Material.all, :id, :name, {}) %>
    </div>
    <div class="mb-2">
      <%= f.label :"板厚：" %>
      <%= f.text_field :thickness %>mm
    </div>
    <div class="mb-2">
      <%= f.label :"質量：" %>
      <%= f.text_field :weight %>g
    </div>
    <div class="mb-2">
      <%= f.label :"仕入先：" %>
      <%= f.collection_select(:supplier_id, Supplier.all, :id, :name, {}) %>
    </div>
    <div class="mb-2">
      <%= f.label :"承認日：" %>
      <%= f.date_select :approval_date, start_year: 2000, end_year:(Time.now.year) %>
    </div>
    <div class="mb-4">
      <%= f.label :"参考部品：" %>
      <%= f.collection_select(:reference_parts, Part.order(:product_number), :product_number, :product_number, prompt: "--") %>
    </div>
    <%= f.submit '登録する', class: 'form-submit p-2' %>
  <% end %>
</div>

<div id="page_top">
  <a href="#"><i class="arrow fas fa-arrow-up text-3xl"></i></a>
</div>

app/views/parts/search.html.erb
<div class="p-8 pb-0 text-3xl font-bold" >
  検索結果
</div>

<div class="row row-cols-1 row-cols-md-3 g-4 m-4">
  <% if @results.length != 0 %>
    <% @results.each do |result| %>
      <div class="col hide_area">
        <div class="card">
          <div>
            <i class="far fa-times-circle fa-pull-right fa-border hover:text-blue-400 cursor-pointer text-xl hide_btn"></i>
          </div>
          <div class="slider m-4">
            <% result.images.each do |image| %>
              <%= image_tag image.variant(resize: "400x400"), id: 'part_image' %>
            <% end %>
          </div>
          <div class="ml-4 mr-4">
            <div class="p-1 bg-gray-200 rounded-md">
              車種：<%= result.car_model.car_model_code %>
            </div>
            <div class="mt-2">
              部品名 ： <%= result.part_name.name %>
            </div>
            <div class="mt-2 p-1 bg-gray-200 rounded-md">
              品番 ： <%= result.product_number %>
            </div>
            <div class="mt-2">
              材質 ： <%= result.material.name %>
            </div>
            <div class="mt-2 p-1 bg-gray-200 rounded-md">
              板厚 ： <%= result.thickness %>mm
            </div>
            <div class="mt-2">
              質量 ： <%= result.weight %>g
            </div>
            <div class="mt-2 p-1 bg-gray-200 rounded-md">
              仕入先 ： <%= result.supplier.name %>
            </div>
          </div>
          <div class="grid justify-items-stretch">
            <button class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 m-2 px-2 rounded justify-self-center">
              <%= link_to "さらに詳しく", car_model_part_path(result.car_model.id, result.id) %>
            </button>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    該当する部品はありません
  <% end %>
</div>

<div id="page_top">
  <a href="#"><i class="arrow fas fa-arrow-up text-3xl"></i></a>
</div>

app/views/parts/show.html.erb
<div class="flex wrapper h-screen">
  <div class="m-8 slider show_slider">
    <% @part.images.each do |image| %>
      <%= image_tag image, name: 'part[images][]' %>
    <% end %>
  </div>
  <div class="p-8 m-4 bg-white rounded-md border-4 border-gray-600">
    <div class="p-1 sm:text-1xl md:text-2xl bg-gray-200 rounded-md">
      車種：<%= @part.car_model.car_model_code %>
    </div>
    <div class="mt-2 sm:text-1xl md:text-2xl">
      部品名 ： <%= @part.part_name.name %>
    </div>
    <div class="mt-2 p-1 sm:text-1xl md:text-2xl bg-gray-200 rounded-md">
      品番 ： <%= @part.product_number %>
    </div>
    <div class="mt-2 sm:text-1xl md:text-2xl">
      材質 ： <%= @part.material.name %>
    </div>
    <div class="mt-2 sm:text-1xl md:text-2xl p-1 bg-gray-200 rounded-md">
      板厚 ： <%= @part.thickness %>mm
    </div>
    <div class="mt-2 sm:text-1xl md:text-2xl">
      質量 ： <%= @part.weight %>g
    </div>
    <div class="mt-2 p-1 sm:text-1xl md:text-2xl bg-gray-200 rounded-md">
      仕入先 ： <%= @part.supplier.name %>
    </div>
    <div class="mt-8 sm:text-1xl md:text-1xl" >
      承認日 ： <%= @part.approval_date %>
    </div>
    <div class="mt-2 sm:text-1xl md:text-1xl" >
      登録者 ： <%= @part.user.name %>
    </div>
    <% if @part.reference_parts.presence %>
      <div class="mt-2 sm:text-1xl md:text-1xl" >
        参考部品 ： <%= @part.reference_parts %>
      </div>
    <% end %>
    <% if @part.user.id == current_user.id %>
      <div class="flex justify-center">
        <div class="mt-10 text-xs">
          <button class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 m-2 px-2 rounded">
            <%= link_to "修正する", edit_car_model_part_path %>
          </button>
        </div>
        <div class="mt-10 text-xs">
          <button class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 m-2 px-2 rounded">
            <%= link_to "削除する", car_model_part_path, method: :delete, data: {confirm: "品番：#{@part.product_number} 削除しますか？"} %>
          </button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  <div class="p-8 bg-gray-900 flex items-center text-gray-50 justify-between">
    <%= link_to "CompareParts", root_path, class: "font-bold text-4xl" %> 
  
    <div class="flex">
      <% if user_signed_in? %>
      <div class="mx-10">
        <%= current_user.name %>さん
      </div>
      <div class="float-right">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </div>
      <% else %>
      <div class="mx-10">
        <%= link_to "ログイン", new_user_session_path %>
      </div>
      <div>
        <%= link_to "新規登録", new_user_registration_path %>
      </div>
      <% end %>
    </div>
  </div>
  <div>
        
    
    </div>
  </div>
</header>